src/tp1_sesiones/Final/blog/urls.py
from  django.urls import path
from .views import render_posts,post_detail


app_name='blog'

urlpatterns=[   
    path("",render_posts,name='posts'),
    path("<int:post_id>",post_detail, name="post_detail"),
]

src/tp1_sesiones/Final/django_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/',include('blog.urls')),
    path('webinicio/', include('webinicio.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tp1_sesiones/Final/webinicio/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

src/tp1_sesiones/Final/blog/models.py
from django.db import models
import datetime


class Posts(models.Model):
    
    titulo=models.CharField(max_length=100)
    descripcion=models.TextField()
    image=models.ImageField(upload_to='blog/images')
    fecha=models.DateField(datetime.date.today)

src/tp1_sesiones/Final/portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):

    titulo = CharField(max_length=100)
    descripcion = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)

src/tp1_sesiones/Final/webinicio/models.py
from django.db import models

class AuditoriaFecha(models.Model):
    f_creacion = models.DateTimeField(auto_now_add=True)
    f_actualizacion = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Usuario(AuditoriaFecha):
    usuario = models.CharField(max_length=255)
    clave = models.CharField(max_length=255)

class Persona(AuditoriaFecha):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    f_nacimiento = models.DateField()
    usuario = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)

class UsuarioRegistrado(models.Model):
    imagen = models.ImageField(upload_to='user_images/', blank=True, null=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    cedula = models.CharField(max_length=20)
    correo = models.EmailField()
    usuario = models.CharField(max_length=50)
    contraseña = models.CharField(max_length=100)
    habilidades = models.TextField()
    herramientas = models.TextField()

src/tp1_sesiones/Final/webinicio/forms.py
from django import forms
from .models import Usuario,Persona
from .models import UsuarioRegistrado


class LoginForm(forms.Form):
    usuario = forms.CharField(required=True,widget=forms.EmailInput())
    clave = forms.CharField(required=True,widget=forms.PasswordInput())
    
    class Meta:
        model = Usuario
class RegistroForm(forms.ModelForm):
    class Meta:
        model = UsuarioRegistrado
        fields = ['imagen', 'nombre', 'apellido', 'cedula', 'correo', 'usuario', 'contraseña', 'habilidades', 'herramientas']
        widgets = {
            'contraseña': forms.PasswordInput(),
        }

src/tp1_sesiones/Final/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Posts

def render_posts(request):
    posts=Posts.objects.all()
    return render(request,'posts.html',{'posts':posts})

def post_detail(request,post_id):
    post=get_object_or_404(Posts,pk=post_id)
    return render(request,'post_detail.html',{"post":post})

src/tp1_sesiones/Final/portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects=Project.objects.all()   
    return render(request,'home.html',{'projects':projects})

src/tp1_sesiones/Final/webinicio/views.py
# accounts/views.py

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')  
        else:
            messages.error(request, 'Credenciales inválidas')
    return render(request, 'accounts/login.html')

def user_logout(request):
    logout(request)
    return redirect('index') 

src/tp1_sesiones/Final/blog/templates/post_detail.html
{% extends 'layout.html'%}

{% block content%}

<div class="text-center">
    <h1>{{post.titulo}}</h1>
<h3 class="my-2 h5 text-muted">{{post.fecha|date:'d M Y'|upper}}</h3>

<img src="{{post.image.url}}" alt="{{post.titulo}}" class="img-fluid">

<div class="my-4">
    <p>{{post.descripcion|safe}}</p>
</div>
</div>


{%endblock%}

src/tp1_sesiones/Final/blog/templates/posts.html
{% extends 'layout.html' %}

{% block content%}

<h1>Post</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.titulo}}"  class="img-fluid">
            </div>
            <div class="col-9">
                <h2>{{post.titulo}}</h2>
                <p>{{post.descripcion|striptags|truncatechars:100}}</p>
                <p>{{post.fecha|date:'d M Y'|upper}}</p>

                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.titulo}}</a>
            </div>
        </div>
    </div>
</div>






{% endfor %}

{%endblock%}

src/tp1_sesiones/Final/portfolio/templates/home.html
{% extends 'layout.html'%}

{% block content%}

{% load static %}

<header class="row bg-black">
    <div class="col-md-4">
      <img src="{% static 'portfolio/profile-img.jpg' %}" alt="Perfil de Jose Miguel Botero" class="img-fluid">
    </div>
    <div class="col-md-8 align-self-center">
      <h1>I am <strong>Jose Miguel Botero</strong></h1>
      <h3>I am a Java Full Stack Developer</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit aliquid quos officia fugit repudiandae expedita porro unde autem. Fuga unde, molestiae similique eligendi exercitationem quas totam corrupti facilis magnam sint distinctio excepturi quod cumque hic, corporis consequatur dolor sed aliquid nisi sunt vel! Iure doloremque quod architecto laudantium, debitis ea explicabo obcaecati ut, cumque commodi ipsam culpa non tenetur excepturi harum ratione consequuntur velit facilis cum voluptatum optio, sunt nihil! Quasi fuga eligendi qui labore culpa quidem facere dolorem quo obcaecati laboriosam rem rerum, ipsam accusamus magnam? Placeat iure, adipisci at ullam natus odio, quisquam molestias tempora optio impedit facere..</p>
      <a href="{% static 'portfolio/cv.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Descargar CV</a>
    </div>
  </header>
  
<div class="row my-4 text-center">

    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus perspiciatis quaerat aspernatur nemo nisi sunt, distinctio impedit pariatur ipsum optio?</p>

    {%for project in  projects%}

    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <div class="card-body">
                <h2 class="text-white">{{project.titulo}}</h2>
                <p class="text-white">{{project.descripcion}}</p>
                <img src="{{project.image.url}}" alt="{{project.titulo}}" class="img-img-top">
                <div class="mt-3">
                    {% if project.url %}
                        <a href="{{project.url}}" class="btn bg-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    
    

{%endfor%}

{%endblock %}
</div>

src/tp1_sesiones/Final/portfolio/templates/layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pacial Final</title> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css'%}">
  </head>
</head>
<body class="text-light">

  {%load static%}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand fw-bold fst-italic" href="/">Final</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto"> 
        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
        <a class="nav-item nav-link" href="{% url 'blog:posts'%}">Blog</a>
        <a class="btn btn-primary btn-sm mx-2" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Descargar CV</a> 
      </div>
    </div>
  </nav>  
  
    <div class="conteiner p-4">

      {% block content %}

      {% endblock %}
  

    </div>
</body>
</html>

src/tp1_sesiones/Final/webinicio/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Login - Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/login.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: iPortfolio
  * Updated: Sep 18 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="{% static 'img/profile-img.jpg' %}" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="{% url 'inicio' %}">Alex Smith</a></h1>
      </div>

      <nav id="navbar" class="nav-menu navbar">
        <ul>
          <li><a href="{% url 'inicio' %}" >Inicio</a></li>
          <li><a href="{% url 'registro' %}" >Registro</a></li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Login</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Login</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <div class="login-wrapper">
          <div class="login-side">
              <a href="#" title="Logo">
                  <img class="logo" src="assets/logo.png" alt="Logo">
              </a>
              <div class="my-form__wrapper">
                  <div class="login-welcome-row">
                      <h1>{{ mensaje }} &#x1F44F;</h1>
                      <p>Por Favor ingrese sus credenciales!</p>
                  </div>
                  <form class="my-form" method = "POST">
                      {% csrf_token %}
                      {% comment %} <div class="divider">
                          <div class="divider-line"></div>
                          Or
                          <div class="divider-line"></div>
                      </div> {% endcomment %}
                      <div class="text-field">
                          <label for="email">Usuario/Email:</label>
                           {{ form_login.usuario }} 
                           {% comment %} <input
                              type="email"
                              id="email"
                              name="email"
                              placeholder="Your Email"
                              required
                          >  {% endcomment %}
                          <img
                              alt="Email Icon"
                              title="Email Icon"
                              src="assets/email.svg"
                          >
                      </div>
                      <div class="text-field">
                          <label for="password">Clave:</label>
                          {{ form_login.clave }}
                          {% comment %} <input
                              id="password"
                              type="password"
                              name="password"
                              placeholder="Your Password"
                              title="Minimum 6 characters at 
                                  least 1 Alphabet and 1 Number"
                              pattern="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$"
                              required
                          > {% endcomment %}
                          <img
                              alt="Password Icon"
                              title="Password Icon"
                              src="assets/password.svg"
                          >
                      </div>
                      <input type="submit" class="my-form__button" value="Login">
                      <div class="my-form__actions">
                          <div class="my-form__row">
                              <span>Did you forget your password?</span>
                              <a href="#" title="Reset Password">
                                  Reset Password
                              </a>
                          </div>
                          <div class="my-form__signup">
                              <a href="#" title="Create Account">
                                  Create Account
                              </a>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
          <div class="info-side">
              <img src="assets/mock.png" alt="Mock" class="mockup">
              <div class="welcome-message">
                  <h2>Navitron Maps! 👋</h2>
                  <p>
                     Your ultimate guide to navigating the world 
                     and discovering new places with ease.
                  </p>    
              </div>
          </div>
      </div>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>iPortfolio</span></strong>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/typed.js/typed.umd.js' %}"></script>
  <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>